apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-app
  namespace: iti
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      name: finance-redis
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx
