apiVersion: v1
kind: Service
metadata:
  name: port-backend
  namespace: haproxy-controller-devops
spec:
  type: ClusterIP
  selector:
    run: ingress-default-backend
  ports:
    - port: 80
      targetPort: 8080
