# kubectl create secret generic db-secret --from-literal=MYSQL_DATABASE=sql01   --from-literal=MYSQL_USER=user   --from-literal=MYSQL_PASSWORD=password --from-literal=MYSQL_ROOT_PASSWORD=password123
apiVersion: v1
kind: Pod
metadata:
  name: db-pod
spec:
  containers:
    - name: mysql
      image: mysql:5.7
      envFrom:
        - secretRef:
            name: db-secret
