apiVersion: v1
kind: Pod
metadata:
  name: red
spec:
  initContainers:
    - name: lemon
      image: busybox
      command: ["/bin/sh","-c"]
      args:
        - sleep 20
  containers:
    - name: gold
      image: redis
