apiVersion: v1
kind: Pod
metadata:
  name: live-probe-test
spec:
  containers:
    - name: nginx-pod
      image: nginx
      livenessProbe:
        httpGet:
          path: /
          port: 80
        periodSeconds: 5
        failureThreshold: 3
