apiVersion: v1
kind: Pod
metadata:
  name: probe-test
spec:
  containers:
    - name: nginx-pod
      image: nginx
      startupProbe:
        exec:
          command:
            - curl
            - localhost
        periodSeconds: 5
        failureThreshold: 3
