apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
spec:
  volumes:
    - name: nginx-confmap
      configMap:
        name: nginx-config
  containers:
    - name: nginx-pod
      image: nginx
      volumeMounts:
        - mountPath: /etc/nginx
          name: nginx-confmap
