apiVersion: v1
kind: Pod
metadata:
  name: webserver
spec:
  volumes:
    - name: shared-logs
      emptyDir:
        sizeLimit: 200Mi
  containers:
    - name: "nginx-container"
      image: nginx:latest
      volumeMounts:
        - mountPath: /var/log/nginx
          name: shared-logs

    - name: "sidecar-container"
      image: ubuntu:latest
      command:
        - /bin/bash
        - -c
      args:
        - while true; do cat  /var/log/nginx/access.log /var/log/nginx/error.log; sleep 30; done
      volumeMounts:
        - mountPath: /var/log/nginx
          name: shared-logs
