apiVersion: v1 
kind: Pod 
metadata: 
  name: volume-share-datacenter
spec:
  volumes:
    - name: volume-share
      emptyDir: 
        sizeLimit: 200Mi
  containers:
    - name: volume-container-datacenter-1
      image: centos
      command:
        - /bin/bash
        - -c
      args:
        - sleep 10000
      volumeMounts:
        - mountPath: /tmp/news
          name: volume-share
  
    - name: volume-container-datacenter-2
      image: centos
      command:
        - /bin/bash
        - -c
      args:
        - sleep 10000
      volumeMounts:
        - mountPath: /tmp/cluster
          name: volume-share
